"""empty message

Revision ID: 5ddacbbcfac5
Revises: 8f853d592244
Create Date: 2019-02-27 03:27:37.681000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ddacbbcfac5'
down_revision = '8f853d592244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'email',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=20),
               nullable=True)
    op.drop_index('email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(collation=u'utf8_bin', length=20), nullable=False))
    op.create_index('email', 'user', ['email'], unique=True)
    op.alter_column('staff', 'email',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=20),
               nullable=False)
    # ### end Alembic commands ###
