"""empty message

Revision ID: c2763589afad
Revises: 1be015d332ff
Create Date: 2019-05-07 13:41:07.517215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2763589afad'
down_revision = '1be015d332ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('comment', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
