"""empty message

Revision ID: ee2999889fd9
Revises: c2763589afad
Create Date: 2019-05-07 17:50:54.733866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2999889fd9'
down_revision = 'c2763589afad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'location_id')
    # ### end Alembic commands ###
