
LOGIN_ERROR_MAX_TIMES = 5

#in sec
LOGIN_ERROR_FORBID_TIME = 600

#cache time of location info
LOCATION_REDIS_CACHE_EXPIRES = 720

QINIU_URL_DOMAIN ='http://pqla51t0s.bkt.gdipper.com/'

HOME_PAGE_MAX_BIKES = 10

HOME_PAGE_DATA_REDIS_EXPIRES = 720

BIKE_DETAIL_REDIS_EXPIRE_SECOND = 720

BIKE_DETAIL_COMMENT_DISPLAY_COUNTS= 720

BIKE_LIST_PAGE_REDIS_CACHE_EXPIRES = 10

BIKE_LIST_PAGE_CAPACITY = 8


